#!/bin/bash

# Base directory for the project
BASE_DIR="my_flask_app"

# Create the main project directory
mkdir -p "$BASE_DIR"

# Create subdirectories
mkdir -p "$BASE_DIR/app/domain/user"
mkdir -p "$BASE_DIR/app/domain/session"
mkdir -p "$BASE_DIR/app/domain/authentication"
mkdir -p "$BASE_DIR/app/application/user"
mkdir -p "$BASE_DIR/app/application/session"
mkdir -p "$BASE_DIR/app/application/authentication"
mkdir -p "$BASE_DIR/app/infrastructure/repositories"
mkdir -p "$BASE_DIR/app/infrastructure/services"
mkdir -p "$BASE_DIR/app/interfaces/api"
mkdir -p "$BASE_DIR/app/migrations"
mkdir -p "$BASE_DIR/config"
mkdir -p "$BASE_DIR/tests/unit"
mkdir -p "$BASE_DIR/tests/integration"

# Create files for the project
touch "$BASE_DIR/app/__init__.py"
touch "$BASE_DIR/app/domain/user/__init__.py"
touch "$BASE_DIR/app/domain/user/models.py"
touch "$BASE_DIR/app/domain/user/services.py"
touch "$BASE_DIR/app/domain/user/repository.py"
touch "$BASE_DIR/app/domain/session/__init__.py"
touch "$BASE_DIR/app/domain/session/models.py"
touch "$BASE_DIR/app/domain/session/services.py"
touch "$BASE_DIR/app/domain/session/repository.py"
touch "$BASE_DIR/app/domain/authentication/__init__.py"
touch "$BASE_DIR/app/domain/authentication/models.py"
touch "$BASE_DIR/app/domain/authentication/services.py"
touch "$BASE_DIR/app/domain/authentication/repository.py"
touch "$BASE_DIR/app/application/user/__init__.py"
touch "$BASE_DIR/app/application/user/commands.py"
touch "$BASE_DIR/app/application/user/queries.py"
touch "$BASE_DIR/app/application/user/handlers.py"
touch "$BASE_DIR/app/application/session/__init__.py"
touch "$BASE_DIR/app/application/session/commands.py"
touch "$BASE_DIR/app/application/session/queries.py"
touch "$BASE_DIR/app/application/session/handlers.py"
touch "$BASE_DIR/app/application/authentication/__init__.py"
touch "$BASE_DIR/app/application/authentication/commands.py"
touch "$BASE_DIR/app/application/authentication/queries.py"
touch "$BASE_DIR/app/application/authentication/handlers.py"
touch "$BASE_DIR/app/infrastructure/repositories/user_repository.py"
touch "$BASE_DIR/app/infrastructure/repositories/session_repository.py"
touch "$BASE_DIR/app/infrastructure/repositories/authentication_repository.py"
touch "$BASE_DIR/app/infrastructure/services/email_service.py"
touch "$BASE_DIR/app/infrastructure/services/auth_service.py"
touch "$BASE_DIR/app/interfaces/api/__init__.py"
touch "$BASE_DIR/app/interfaces/api/user_routes.py"
touch "$BASE_DIR/app/interfaces/api/session_routes.py"
touch "$BASE_DIR/app/interfaces/api/auth_routes.py"
touch "$BASE_DIR/config/__init__.py"
touch "$BASE_DIR/config/settings.py"
touch "$BASE_DIR/tests/unit/__init__.py"
touch "$BASE_DIR/tests/unit/test_user.py"
touch "$BASE_DIR/tests/unit/test_session.py"
touch "$BASE_DIR/tests/unit/test_authentication.py"
touch "$BASE_DIR/tests/integration/__init__.py"
touch "$BASE_DIR/tests/integration/test_user_integration.py"
touch "$BASE_DIR/tests/integration/test_session_integration.py"
touch "$BASE_DIR/tests/integration/test_authentication_integration.py"
touch "$BASE_DIR/app.py"
touch "$BASE_DIR/requirements.txt"
touch "$BASE_DIR/README.md"

echo "Project structure created successfully."
