[project]
name = "general-user"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
used-python = "3.12"
requires-python = ">=3.12"
dependencies = [
    "knowledge-engineering",
]

[tool.uv.sources]
knowledge-engineering = { path = "../../" }
